#服务器基本信息
server:
  #服务器内网ip，用于上报grpc地址，当可以获取多个内网ip的时候，代码获取的不准确
  serverIp: 192.168.110.234
  #tcp端口（外网）
  outPort: 0
  #tcp端口（内网）
  inPort: 0
  #http端口（外网）
  httpPort: 0
  #grpc端口（内网）
  grpcPort: 19551
  #服务器Id
  serverId: 21201
  # 服务器的HTTP端口，默认为80
  port: 19501
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 5
  # solana相关配置
  solana:
    # 元数据存放地址（访问元数据所在服务器域名）https://tokyostupidgames.io    http://192.168.110.234:19401
    metaUri: https://tokyostupidgames.io
    # 智能合约程序地址
    programId: xxx

# 项目相关配置
orange-web:
  # 文件上传下载路径示例（项目运行根目录下）
  profile: uploads/
  # tsg项目上传资源（项目运行根目录下）
  tsg: tsg/

# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  #mongodb
  data:
    mongodb:
      #db库连接地址 47.108.135.62 192.168.110.111
      uri: mongodb://xxx:xxx@192.168.110.111:27017/webgame_game?authSource=admin
      #配置库连接地址（自定义）
      data:
        uri: mongodb://xxx:xxx@192.168.110.111:27017/webgame_game_data?authSource=admin
      logs:
        uri: mongodb://xxx:xxx@192.168.110.111:27017/webgame_game_log?authSource=admin
      #根据注解自动生成mongo索引
      auto-index-creation: true
      #生成复合索引，下面的注解放在实体类名上面
      #@Document
      #@CompoundIndexes({ @CompoundIndex(name = "oIndex", def = "{'userId': 1, 'payState': 1}") })
      #或者单个索引，放在字段名字上面
      #@Indexed(unique = true)