// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publicChatMessage.proto
// Protobuf Java Version: 4.26.1

package com.game.publicchatserver.proto;

public final class PublicChatProto {
  private PublicChatProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      PublicChatProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqPublicChatServerRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqPublicChatServerRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    int getServerInfoCount();
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    boolean containsServerInfo(
        int key);
    /**
     * Use {@link #getServerInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getServerInfo();
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getServerInfoMap();
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    /* nullable */
java.lang.String getServerInfoOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    java.lang.String getServerInfoOrThrow(
        int key);
  }
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ReqPublicChatServerRegister_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ReqPublicChatServerRegister_fieldAccessorTable;
  /**
   * <pre>
   * 返回向聊天服务器注册 msgId=209201
   * </pre>
   *
   * Protobuf type {@code ResPublicChatServerRegister}
   */
  public static final class ResPublicChatServerRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResPublicChatServerRegister)
      ResPublicChatServerRegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResPublicChatServerRegister.class.getName());
    }
    // Use ResPublicChatServerRegister.newBuilder() to construct.
    private ResPublicChatServerRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResPublicChatServerRegister() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServerRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServerRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.class, com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister)) {
        return super.equals(obj);
      }
      com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister other = (com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回向聊天服务器注册 msgId=209201
     * </pre>
     *
     * Protobuf type {@code ResPublicChatServerRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResPublicChatServerRegister)
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServerRegister_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServerRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.class, com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.Builder.class);
      }

      // Construct using com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServerRegister_descriptor;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister getDefaultInstanceForType() {
        return com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister build() {
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister buildPartial() {
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister result = new com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister) {
          return mergeFrom((com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister other) {
        if (other == com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResPublicChatServerRegister)
    }

    // @@protoc_insertion_point(class_scope:ResPublicChatServerRegister)
    private static final com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister();
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResPublicChatServerRegister>
        PARSER = new com.google.protobuf.AbstractParser<ResPublicChatServerRegister>() {
      @java.lang.Override
      public ResPublicChatServerRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResPublicChatServerRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResPublicChatServerRegister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServerRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ReqPublicChatServerRegister_ServerInfoEntry_descriptor;
  /**
   * <pre>
   * 聊天服务器to游戏服务器之间心跳 msgId=209202
   * </pre>
   *
   * Protobuf type {@code ResPublicChatServer2ServerHeartbeat}
   */
  public static final class ResPublicChatServer2ServerHeartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResPublicChatServer2ServerHeartbeat)
      ResPublicChatServer2ServerHeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResPublicChatServer2ServerHeartbeat.class.getName());
    }
    // Use ResPublicChatServer2ServerHeartbeat.newBuilder() to construct.
    private ResPublicChatServer2ServerHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResPublicChatServer2ServerHeartbeat() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServer2ServerHeartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServer2ServerHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.class, com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat)) {
        return super.equals(obj);
      }
      com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat other = (com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 聊天服务器to游戏服务器之间心跳 msgId=209202
     * </pre>
     *
     * Protobuf type {@code ResPublicChatServer2ServerHeartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResPublicChatServer2ServerHeartbeat)
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServer2ServerHeartbeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServer2ServerHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.class, com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.Builder.class);
      }

      // Construct using com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ResPublicChatServer2ServerHeartbeat_descriptor;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat getDefaultInstanceForType() {
        return com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat build() {
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat buildPartial() {
        com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat result = new com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat) {
          return mergeFrom((com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat other) {
        if (other == com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResPublicChatServer2ServerHeartbeat)
    }

    // @@protoc_insertion_point(class_scope:ResPublicChatServer2ServerHeartbeat)
    private static final com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat();
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResPublicChatServer2ServerHeartbeat>
        PARSER = new com.google.protobuf.AbstractParser<ResPublicChatServer2ServerHeartbeat>() {
      @java.lang.Override
      public ResPublicChatServer2ServerHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResPublicChatServer2ServerHeartbeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResPublicChatServer2ServerHeartbeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.publicchatserver.proto.PublicChatProto.ResPublicChatServer2ServerHeartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ReqPublicChatServerRegister_ServerInfoEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ResPublicChatServerRegister_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ResPublicChatServerRegister_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ResPublicChatServer2ServerHeartbeat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ResPublicChatServer2ServerHeartbeat_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\027publicChatMessage.proto\"\222\001\n\033ReqPublicC" +
                        "hatServerRegister\022@\n\nserverInfo\030\001 \003(\0132,." +
                        "ReqPublicChatServerRegister.ServerInfoEn" +
                        "try\0321\n\017ServerInfoEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005v" +
                        "alue\030\002 \001(\t:\0028\001\"\035\n\033ResPublicChatServerReg" +
                        "ister\"%\n#ResPublicChatServer2ServerHeart" +
                        "beatB2\n\037com.game.publicchatserver.protoB" +
                        "\017PublicChatProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_ReqPublicChatServerRegister_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ReqPublicChatServerRegister_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ReqPublicChatServerRegister_descriptor,
                new java.lang.String[]{"ServerInfo",});
        internal_static_ReqPublicChatServerRegister_ServerInfoEntry_descriptor =
                internal_static_ReqPublicChatServerRegister_descriptor.getNestedTypes().get(0);
        internal_static_ReqPublicChatServerRegister_ServerInfoEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ReqPublicChatServerRegister_ServerInfoEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_ResPublicChatServerRegister_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ResPublicChatServerRegister_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ResPublicChatServerRegister_descriptor,
                new java.lang.String[]{});
        internal_static_ResPublicChatServer2ServerHeartbeat_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_ResPublicChatServer2ServerHeartbeat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_ResPublicChatServer2ServerHeartbeat_descriptor,
                new java.lang.String[]{});
        descriptor.resolveAllFeaturesImmutable();
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ResPublicChatServerRegisterOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ResPublicChatServerRegister)
      com.google.protobuf.MessageOrBuilder {
  }

    public interface ResPublicChatServer2ServerHeartbeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ResPublicChatServer2ServerHeartbeat)
            com.google.protobuf.MessageOrBuilder {
  }

  /**
   * <pre>
   * 请求向聊天服务器注册 msgId=209101		-----返回消息  msgId=209201
   * </pre>
   *
   * Protobuf type {@code ReqPublicChatServerRegister}
   */
  public static final class ReqPublicChatServerRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqPublicChatServerRegister)
      ReqPublicChatServerRegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqPublicChatServerRegister.class.getName());
    }
    // Use ReqPublicChatServerRegister.newBuilder() to construct.
    private ReqPublicChatServerRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqPublicChatServerRegister() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetServerInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.class, com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.Builder.class);
    }

    public static final int SERVERINFO_FIELD_NUMBER = 1;
    private static final class ServerInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                      com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_ServerInfoEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> serverInfo_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetServerInfo() {
      if (serverInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ServerInfoDefaultEntryHolder.defaultEntry);
      }
      return serverInfo_;
    }
    public int getServerInfoCount() {
      return internalGetServerInfo().getMap().size();
    }
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    @java.lang.Override
    public boolean containsServerInfo(
        int key) {

      return internalGetServerInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getServerInfoMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getServerInfo() {
      return getServerInfoMap();
    }
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.String> getServerInfoMap() {
      return internalGetServerInfo().getMap();
    }
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getServerInfoOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetServerInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getServerInfoOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetServerInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetServerInfo(),
          ServerInfoDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetServerInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        serverInfo__ = ServerInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, serverInfo__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister)) {
        return super.equals(obj);
      }
      com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister other = (com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister) obj;

      if (!internalGetServerInfo().equals(
          other.internalGetServerInfo())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetServerInfo().getMap().isEmpty()) {
        hash = (37 * hash) + SERVERINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetServerInfo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求向聊天服务器注册 msgId=209101		-----返回消息  msgId=209201
     * </pre>
     *
     * Protobuf type {@code ReqPublicChatServerRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqPublicChatServerRegister)
        com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetServerInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableServerInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.class, com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.Builder.class);
      }

      // Construct using com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableServerInfo().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.publicchatserver.proto.PublicChatProto.internal_static_ReqPublicChatServerRegister_descriptor;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister getDefaultInstanceForType() {
        return com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister build() {
        com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister buildPartial() {
        com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister result = new com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverInfo_ = internalGetServerInfo();
          result.serverInfo_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister) {
          return mergeFrom((com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister other) {
        if (other == com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister.getDefaultInstance()) return this;
        internalGetMutableServerInfo().mergeFrom(
            other.internalGetServerInfo());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
                serverInfo__ = input.readMessage(
                    ServerInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableServerInfo().getMutableMap().put(
                    serverInfo__.getKey(), serverInfo__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> serverInfo_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
          internalGetServerInfo() {
        if (serverInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ServerInfoDefaultEntryHolder.defaultEntry);
        }
        return serverInfo_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
          internalGetMutableServerInfo() {
        if (serverInfo_ == null) {
          serverInfo_ = com.google.protobuf.MapField.newMapField(
              ServerInfoDefaultEntryHolder.defaultEntry);
        }
        if (!serverInfo_.isMutable()) {
          serverInfo_ = serverInfo_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return serverInfo_;
      }
      public int getServerInfoCount() {
        return internalGetServerInfo().getMap().size();
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      @java.lang.Override
      public boolean containsServerInfo(
          int key) {

        return internalGetServerInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getServerInfoMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getServerInfo() {
        return getServerInfoMap();
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, java.lang.String> getServerInfoMap() {
        return internalGetServerInfo().getMap();
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getServerInfoOrDefault(
          int key,
          /* nullable */
java.lang.String defaultValue) {

        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetServerInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getServerInfoOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetServerInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearServerInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableServerInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      public Builder removeServerInfo(
          int key) {

        internalGetMutableServerInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
          getMutableServerInfo() {
        bitField0_ |= 0x00000001;
        return internalGetMutableServerInfo().getMutableMap();
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      public Builder putServerInfo(
          int key,
          java.lang.String value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableServerInfo().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; serverInfo = 1;</code>
       */
      public Builder putAllServerInfo(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableServerInfo().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqPublicChatServerRegister)
    }

    // @@protoc_insertion_point(class_scope:ReqPublicChatServerRegister)
    private static final com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister();
    }

    public static com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqPublicChatServerRegister>
        PARSER = new com.google.protobuf.AbstractParser<ReqPublicChatServerRegister>() {
      @java.lang.Override
      public ReqPublicChatServerRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqPublicChatServerRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqPublicChatServerRegister> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.publicchatserver.proto.PublicChatProto.ReqPublicChatServerRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
