#服务器基本信息
server:
  #服务器内网ip，用于上报grpc地址，当可以获取多个内网ip的时候，代码获取的不准确
  serverIp: 192.168.0.106
  #tcp端口（外网）
  outPort: 0
  #tcp端口（内网）
  inPort: 0
  #http端口（外网）
  httpPort: 0
  #grpc端口（内网）
  grpcPort: 19451
  #服务器Id
  serverId: 21101
  # 服务器的HTTP端口，默认为80
  port: 19401
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 5
  #discord相关
  discord:
    # 机器人 Token
    token: MTI3NDk4OTMyMjAwOTA1NTI1NA.Gvy69b.Cnn5pEQAMiE5TkGxFZz8vWDXbs9bn0YtCJHmE0
    # 登录授权 clientId
    clientId: 1274989322009055254
    # 登录授权 clientSecret
    clientSecret: VGwBCAYfDyJmWdYcaaHp8FOnDkDHMybw
    # 登录授权 accessTokenUrl
    accessTokenUrl: https://discord.com/api/v10/oauth2/token
    # 登录授权 redirectUrl
    redirectUri: https://tokyostupidgames.io
    # 登录授权 获取用户信息url
    userInfoUrl: https://discord.com/api/v10/users/@me
  # twitter相关
  twitter:
    # APP TokyoStupidGame
    # 获取数据 apiKey
#    apiKey: HZTe8LG9ugbMsmxHqvrL3wzSn
#    # 获取数据 Secret Key
#    apiSecretKey: BkRMIpYD4axjeJNpzZqyVMLx1IkW2RrLpd4RIjN8JtDou7QksK
#    # 获取数据 accessToken
#    accessToken: 1802732834052042752-b3JRvskjyNOejoRLxsplzy5NIcde0u
#    # 获取数据 access Token Secret
#    accessTokenSecret: ZmGdXpxeBaBGz1hbeljJay55VMk7lO0S5dOLb0gGSqNxI
#    # 需要分享的内容包含的链接（任务：分享关于tsg的文章）
#    shareUrl: https://tokyostupidgames.io
#    # 获取数据 bearerToken
#    bearerToken: AAAAAAAAAAAAAAAAAAAAABfGvgEAAAAAmiKKG%2FnkpQOxlVk28Kzm1fk3z%2FM%3D0Vnq3tBnufRE6LHzxg3KbUVTPCzvREzSKRSlDj1FAkIseJ0dhP
#    # 登录授权
#    clientId: NWd3d2RJTGtUS3dpMmViUjYzWVQ6MTpjaQ
#    # 登录授权
#    clientSecret: lcm8FWHYD5Fs5s9vAe6CWgiCkTwFU6CSMpuv3Y5UzC7kPQpZDa
#    # 登录授权 token url
#    tokenUrl: https://api.twitter.com/2/oauth2/token
#    # 登录授权 redirectUrl
#    redirectUri: https://tokyostupidgames.io
    # APP TokyoStupid
    # 获取数据 apiKey
    apiKey: pKG2IG9eNi0NLSOmfV9JIr8Qa
    # 获取数据 Secret Key
    apiSecretKey: jz3oA6ah5K1O8GzNbjR50b91MX6GObsdZILOL3Q9VOO7eNHyaI
    # 获取数据 accessToken
    accessToken: 1802732834052042752-unWzZtnwQX2we5WmpZwaK6Ugsmx49q
    # 获取数据 access Token Secret
    accessTokenSecret: r61JaaajK22Nh0RR52GU0KDhu796HHqHWshtmwNr7ATae
    # 需要分享的内容包含的链接（任务：分享关于tsg的文章）
    shareUrl: https://tokyostupidgames.io
    # 获取数据 bearerToken
    bearerToken: AAAAAAAAAAAAAAAAAAAAAPgFvgEAAAAAYKB5YET771n5GQnRcP8%2Ba2RE9xs%3DqOxPMl7cBNEiZPgUp4RgecRmA4etJH1PVTKzPJqY20qP6T7bGR
    # 登录授权
    clientId: NlVRWi05ZkFYVzVTX3RkWnBsdkY6MTpjaQ
    # 登录授权
    clientSecret: Ttd684YjC_jYBQJAsWQUVTDdYX9lc1mdsvmU1-8Envx6iZ8BpC
    # 登录授权 token url
    tokenUrl: https://api.twitter.com/2/oauth2/token
    # 登录授权 redirectUrl
    redirectUri: https://tokyostupidgames.io
  # telegram 相关
  telegram:
    # 机器人 Token
    botToken: 7114922232:AAG0WYZAbFDxMUu5LDXMVAx-McuYt2enV4U
    # 机器人 name
    botName: cxnx_bot
  # MoonPay
  moonPay:
    # url
    url: https://api.moonpay.com/v3/currencies/
    # apiKey
    apiKey: pk_test_tF2Du6V1C7BcwuzoJywSaVATf8CK6N3
    # secret
    secret: sk_test_YJm4nYxWvU8mlnlFfQC0v0qytOFqE0
    # webhook
    webhook: wk_test_yH4MaNtg6AXF43YCvRZNnrU3o3945F
  # Google登录
  google:
    # clientId
    clientId: 753235075367-ojfpmgrnold60alog8r8bfapt21k2aut.apps.googleusercontent.com
    # clientSecret
    clientSecret: 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
    # redirectUri  https://tokyostupidgames.com   http://localhost:3050
    redirectUri: https://toysverseparty.com

# 项目相关配置
orange-web:
  # 文件上传下载路径示例（项目运行根目录下）
  profile: uploads/
  # tsg项目上传资源（项目运行根目录下）
  tsg: tsg/

# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  #mongodb
  data:
    mongodb:
      #db库连接地址
      uri: mongodb://orange:Orange_qnmw2018_3@192.168.110.111:27017/webgame_game?authSource=admin
      #配置库连接地址（自定义）
      data:
        uri: mongodb://orange:Orange_qnmw2018_3@192.168.110.111:27017/webgame_game_data?authSource=admin
      logs:
        uri: mongodb://orange:Orange_qnmw2018_3@192.168.110.111:27017/webgame_game_log?authSource=admin
      #根据注解自动生成mongo索引
      auto-index-creation: true
      #生成复合索引，下面的注解放在实体类名上面
      #@Document
      #@CompoundIndexes({ @CompoundIndex(name = "oIndex", def = "{'userId': 1, 'payState': 1}") })
      #或者单个索引，放在字段名字上面
      #@Indexed(unique = true)