// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arenaMessage.proto
// Protobuf Java Version: 4.26.1

package com.game.arena.proto;

public final class ArenaProto {
  private ArenaProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ArenaProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqArenaChallengeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqArenaChallengeList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 请求竞技场挑战列表
   * </pre>
   *
   * Protobuf type {@code ReqArenaChallengeList}
   */
  public static final class ReqArenaChallengeList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqArenaChallengeList)
      ReqArenaChallengeListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqArenaChallengeList.class.getName());
    }
    // Use ReqArenaChallengeList.newBuilder() to construct.
    private ReqArenaChallengeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqArenaChallengeList() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.arena.proto.ArenaProto.internal_static_ReqArenaChallengeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.arena.proto.ArenaProto.internal_static_ReqArenaChallengeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.arena.proto.ArenaProto.ReqArenaChallengeList.class, com.game.arena.proto.ArenaProto.ReqArenaChallengeList.Builder.class);
    }

    /**
     * Protobuf enum {@code ReqArenaChallengeList.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 107101;</code>
       */
      msgID(107101),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 107101;</code>
       */
      public static final int msgID_VALUE = 107101;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 107101: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.arena.proto.ArenaProto.ReqArenaChallengeList.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ReqArenaChallengeList.E_MsgID)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.arena.proto.ArenaProto.ReqArenaChallengeList)) {
        return super.equals(obj);
      }
      com.game.arena.proto.ArenaProto.ReqArenaChallengeList other = (com.game.arena.proto.ArenaProto.ReqArenaChallengeList) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.arena.proto.ArenaProto.ReqArenaChallengeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求竞技场挑战列表
     * </pre>
     *
     * Protobuf type {@code ReqArenaChallengeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqArenaChallengeList)
        com.game.arena.proto.ArenaProto.ReqArenaChallengeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.arena.proto.ArenaProto.internal_static_ReqArenaChallengeList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.arena.proto.ArenaProto.internal_static_ReqArenaChallengeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.arena.proto.ArenaProto.ReqArenaChallengeList.class, com.game.arena.proto.ArenaProto.ReqArenaChallengeList.Builder.class);
      }

      // Construct using com.game.arena.proto.ArenaProto.ReqArenaChallengeList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.arena.proto.ArenaProto.internal_static_ReqArenaChallengeList_descriptor;
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ReqArenaChallengeList getDefaultInstanceForType() {
        return com.game.arena.proto.ArenaProto.ReqArenaChallengeList.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ReqArenaChallengeList build() {
        com.game.arena.proto.ArenaProto.ReqArenaChallengeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ReqArenaChallengeList buildPartial() {
        com.game.arena.proto.ArenaProto.ReqArenaChallengeList result = new com.game.arena.proto.ArenaProto.ReqArenaChallengeList(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.arena.proto.ArenaProto.ReqArenaChallengeList) {
          return mergeFrom((com.game.arena.proto.ArenaProto.ReqArenaChallengeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.arena.proto.ArenaProto.ReqArenaChallengeList other) {
        if (other == com.game.arena.proto.ArenaProto.ReqArenaChallengeList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqArenaChallengeList)
    }

    // @@protoc_insertion_point(class_scope:ReqArenaChallengeList)
    private static final com.game.arena.proto.ArenaProto.ReqArenaChallengeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.arena.proto.ArenaProto.ReqArenaChallengeList();
    }

    public static com.game.arena.proto.ArenaProto.ReqArenaChallengeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqArenaChallengeList>
        PARSER = new com.google.protobuf.AbstractParser<ReqArenaChallengeList>() {
      @java.lang.Override
      public ReqArenaChallengeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqArenaChallengeList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqArenaChallengeList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.arena.proto.ArenaProto.ReqArenaChallengeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResArenaChallengeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResArenaChallengeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    java.util.List<com.game.bean.proto.BeanProto.PlayerInfo> 
        getChallengePlayerInfoList();
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    com.game.bean.proto.BeanProto.PlayerInfo getChallengePlayerInfo(int index);
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    int getChallengePlayerInfoCount();
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    java.util.List<? extends com.game.bean.proto.BeanProto.PlayerInfoOrBuilder> 
        getChallengePlayerInfoOrBuilderList();
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    com.game.bean.proto.BeanProto.PlayerInfoOrBuilder getChallengePlayerInfoOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回竞技场挑战列表
   * </pre>
   *
   * Protobuf type {@code ResArenaChallengeList}
   */
  public static final class ResArenaChallengeList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResArenaChallengeList)
      ResArenaChallengeListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResArenaChallengeList.class.getName());
    }
    // Use ResArenaChallengeList.newBuilder() to construct.
    private ResArenaChallengeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResArenaChallengeList() {
      challengePlayerInfo_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.arena.proto.ArenaProto.internal_static_ResArenaChallengeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.arena.proto.ArenaProto.internal_static_ResArenaChallengeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.arena.proto.ArenaProto.ResArenaChallengeList.class, com.game.arena.proto.ArenaProto.ResArenaChallengeList.Builder.class);
    }

    /**
     * Protobuf enum {@code ResArenaChallengeList.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 107201;</code>
       */
      msgID(107201),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 107201;</code>
       */
      public static final int msgID_VALUE = 107201;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 107201: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.arena.proto.ArenaProto.ResArenaChallengeList.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResArenaChallengeList.E_MsgID)
    }

    public static final int CHALLENGEPLAYERINFO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.game.bean.proto.BeanProto.PlayerInfo> challengePlayerInfo_;
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.game.bean.proto.BeanProto.PlayerInfo> getChallengePlayerInfoList() {
      return challengePlayerInfo_;
    }
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.game.bean.proto.BeanProto.PlayerInfoOrBuilder> 
        getChallengePlayerInfoOrBuilderList() {
      return challengePlayerInfo_;
    }
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    @java.lang.Override
    public int getChallengePlayerInfoCount() {
      return challengePlayerInfo_.size();
    }
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.PlayerInfo getChallengePlayerInfo(int index) {
      return challengePlayerInfo_.get(index);
    }
    /**
     * <pre>
     * 挑战列表
     * </pre>
     *
     * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.PlayerInfoOrBuilder getChallengePlayerInfoOrBuilder(
        int index) {
      return challengePlayerInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < challengePlayerInfo_.size(); i++) {
        output.writeMessage(1, challengePlayerInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < challengePlayerInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, challengePlayerInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.arena.proto.ArenaProto.ResArenaChallengeList)) {
        return super.equals(obj);
      }
      com.game.arena.proto.ArenaProto.ResArenaChallengeList other = (com.game.arena.proto.ArenaProto.ResArenaChallengeList) obj;

      if (!getChallengePlayerInfoList()
          .equals(other.getChallengePlayerInfoList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChallengePlayerInfoCount() > 0) {
        hash = (37 * hash) + CHALLENGEPLAYERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getChallengePlayerInfoList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.arena.proto.ArenaProto.ResArenaChallengeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回竞技场挑战列表
     * </pre>
     *
     * Protobuf type {@code ResArenaChallengeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResArenaChallengeList)
        com.game.arena.proto.ArenaProto.ResArenaChallengeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.arena.proto.ArenaProto.internal_static_ResArenaChallengeList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.arena.proto.ArenaProto.internal_static_ResArenaChallengeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.arena.proto.ArenaProto.ResArenaChallengeList.class, com.game.arena.proto.ArenaProto.ResArenaChallengeList.Builder.class);
      }

      // Construct using com.game.arena.proto.ArenaProto.ResArenaChallengeList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (challengePlayerInfoBuilder_ == null) {
          challengePlayerInfo_ = java.util.Collections.emptyList();
        } else {
          challengePlayerInfo_ = null;
          challengePlayerInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.arena.proto.ArenaProto.internal_static_ResArenaChallengeList_descriptor;
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ResArenaChallengeList getDefaultInstanceForType() {
        return com.game.arena.proto.ArenaProto.ResArenaChallengeList.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ResArenaChallengeList build() {
        com.game.arena.proto.ArenaProto.ResArenaChallengeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.arena.proto.ArenaProto.ResArenaChallengeList buildPartial() {
        com.game.arena.proto.ArenaProto.ResArenaChallengeList result = new com.game.arena.proto.ArenaProto.ResArenaChallengeList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.game.arena.proto.ArenaProto.ResArenaChallengeList result) {
        if (challengePlayerInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            challengePlayerInfo_ = java.util.Collections.unmodifiableList(challengePlayerInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.challengePlayerInfo_ = challengePlayerInfo_;
        } else {
          result.challengePlayerInfo_ = challengePlayerInfoBuilder_.build();
        }
      }

      private void buildPartial0(com.game.arena.proto.ArenaProto.ResArenaChallengeList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.arena.proto.ArenaProto.ResArenaChallengeList) {
          return mergeFrom((com.game.arena.proto.ArenaProto.ResArenaChallengeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.arena.proto.ArenaProto.ResArenaChallengeList other) {
        if (other == com.game.arena.proto.ArenaProto.ResArenaChallengeList.getDefaultInstance()) return this;
        if (challengePlayerInfoBuilder_ == null) {
          if (!other.challengePlayerInfo_.isEmpty()) {
            if (challengePlayerInfo_.isEmpty()) {
              challengePlayerInfo_ = other.challengePlayerInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChallengePlayerInfoIsMutable();
              challengePlayerInfo_.addAll(other.challengePlayerInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.challengePlayerInfo_.isEmpty()) {
            if (challengePlayerInfoBuilder_.isEmpty()) {
              challengePlayerInfoBuilder_.dispose();
              challengePlayerInfoBuilder_ = null;
              challengePlayerInfo_ = other.challengePlayerInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              challengePlayerInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChallengePlayerInfoFieldBuilder() : null;
            } else {
              challengePlayerInfoBuilder_.addAllMessages(other.challengePlayerInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.game.bean.proto.BeanProto.PlayerInfo m =
                    input.readMessage(
                        com.game.bean.proto.BeanProto.PlayerInfo.parser(),
                        extensionRegistry);
                if (challengePlayerInfoBuilder_ == null) {
                  ensureChallengePlayerInfoIsMutable();
                  challengePlayerInfo_.add(m);
                } else {
                  challengePlayerInfoBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.bean.proto.BeanProto.PlayerInfo> challengePlayerInfo_ =
        java.util.Collections.emptyList();
      private void ensureChallengePlayerInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          challengePlayerInfo_ = new java.util.ArrayList<com.game.bean.proto.BeanProto.PlayerInfo>(challengePlayerInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.PlayerInfo, com.game.bean.proto.BeanProto.PlayerInfo.Builder, com.game.bean.proto.BeanProto.PlayerInfoOrBuilder> challengePlayerInfoBuilder_;

      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.PlayerInfo> getChallengePlayerInfoList() {
        if (challengePlayerInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(challengePlayerInfo_);
        } else {
          return challengePlayerInfoBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public int getChallengePlayerInfoCount() {
        if (challengePlayerInfoBuilder_ == null) {
          return challengePlayerInfo_.size();
        } else {
          return challengePlayerInfoBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.PlayerInfo getChallengePlayerInfo(int index) {
        if (challengePlayerInfoBuilder_ == null) {
          return challengePlayerInfo_.get(index);
        } else {
          return challengePlayerInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder setChallengePlayerInfo(
          int index, com.game.bean.proto.BeanProto.PlayerInfo value) {
        if (challengePlayerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.set(index, value);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder setChallengePlayerInfo(
          int index, com.game.bean.proto.BeanProto.PlayerInfo.Builder builderForValue) {
        if (challengePlayerInfoBuilder_ == null) {
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          challengePlayerInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder addChallengePlayerInfo(com.game.bean.proto.BeanProto.PlayerInfo value) {
        if (challengePlayerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.add(value);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder addChallengePlayerInfo(
          int index, com.game.bean.proto.BeanProto.PlayerInfo value) {
        if (challengePlayerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.add(index, value);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder addChallengePlayerInfo(
          com.game.bean.proto.BeanProto.PlayerInfo.Builder builderForValue) {
        if (challengePlayerInfoBuilder_ == null) {
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.add(builderForValue.build());
          onChanged();
        } else {
          challengePlayerInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder addChallengePlayerInfo(
          int index, com.game.bean.proto.BeanProto.PlayerInfo.Builder builderForValue) {
        if (challengePlayerInfoBuilder_ == null) {
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          challengePlayerInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder addAllChallengePlayerInfo(
          java.lang.Iterable<? extends com.game.bean.proto.BeanProto.PlayerInfo> values) {
        if (challengePlayerInfoBuilder_ == null) {
          ensureChallengePlayerInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, challengePlayerInfo_);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder clearChallengePlayerInfo() {
        if (challengePlayerInfoBuilder_ == null) {
          challengePlayerInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public Builder removeChallengePlayerInfo(int index) {
        if (challengePlayerInfoBuilder_ == null) {
          ensureChallengePlayerInfoIsMutable();
          challengePlayerInfo_.remove(index);
          onChanged();
        } else {
          challengePlayerInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.PlayerInfo.Builder getChallengePlayerInfoBuilder(
          int index) {
        return getChallengePlayerInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.PlayerInfoOrBuilder getChallengePlayerInfoOrBuilder(
          int index) {
        if (challengePlayerInfoBuilder_ == null) {
          return challengePlayerInfo_.get(index);  } else {
          return challengePlayerInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public java.util.List<? extends com.game.bean.proto.BeanProto.PlayerInfoOrBuilder> 
           getChallengePlayerInfoOrBuilderList() {
        if (challengePlayerInfoBuilder_ != null) {
          return challengePlayerInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(challengePlayerInfo_);
        }
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.PlayerInfo.Builder addChallengePlayerInfoBuilder() {
        return getChallengePlayerInfoFieldBuilder().addBuilder(
            com.game.bean.proto.BeanProto.PlayerInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.PlayerInfo.Builder addChallengePlayerInfoBuilder(
          int index) {
        return getChallengePlayerInfoFieldBuilder().addBuilder(
            index, com.game.bean.proto.BeanProto.PlayerInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 挑战列表
       * </pre>
       *
       * <code>repeated .PlayerInfo challengePlayerInfo = 1;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.PlayerInfo.Builder> 
           getChallengePlayerInfoBuilderList() {
        return getChallengePlayerInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.PlayerInfo, com.game.bean.proto.BeanProto.PlayerInfo.Builder, com.game.bean.proto.BeanProto.PlayerInfoOrBuilder> 
          getChallengePlayerInfoFieldBuilder() {
        if (challengePlayerInfoBuilder_ == null) {
          challengePlayerInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.bean.proto.BeanProto.PlayerInfo, com.game.bean.proto.BeanProto.PlayerInfo.Builder, com.game.bean.proto.BeanProto.PlayerInfoOrBuilder>(
                  challengePlayerInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          challengePlayerInfo_ = null;
        }
        return challengePlayerInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ResArenaChallengeList)
    }

    // @@protoc_insertion_point(class_scope:ResArenaChallengeList)
    private static final com.game.arena.proto.ArenaProto.ResArenaChallengeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.arena.proto.ArenaProto.ResArenaChallengeList();
    }

    public static com.game.arena.proto.ArenaProto.ResArenaChallengeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResArenaChallengeList>
        PARSER = new com.google.protobuf.AbstractParser<ResArenaChallengeList>() {
      @java.lang.Override
      public ResArenaChallengeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResArenaChallengeList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResArenaChallengeList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.arena.proto.ArenaProto.ResArenaChallengeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqArenaChallengeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqArenaChallengeList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResArenaChallengeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResArenaChallengeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022arenaMessage.proto\032\nbean.proto\"8\n\025ReqA" +
      "renaChallengeList\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n" +
      "\005msgID\020\335\304\006\"b\n\025ResArenaChallengeList\022(\n\023c" +
      "hallengePlayerInfo\030\001 \003(\0132\013.PlayerInfo\"\037\n" +
      "\007E_MsgID\022\007\n\003def\020\000\022\013\n\005msgID\020\301\305\006B\"\n\024com.ga" +
      "me.arena.protoB\nArenaProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.bean.proto.BeanProto.getDescriptor(),
        });
    internal_static_ReqArenaChallengeList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqArenaChallengeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqArenaChallengeList_descriptor,
        new java.lang.String[] { });
    internal_static_ResArenaChallengeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResArenaChallengeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResArenaChallengeList_descriptor,
        new java.lang.String[] { "ChallengePlayerInfo", });
    descriptor.resolveAllFeaturesImmutable();
    com.game.bean.proto.BeanProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
