// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: questMessage.proto
// Protobuf Java Version: 4.26.1

package com.game.quest.proto;

public final class QuestProto {
  private QuestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      QuestProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqQuestAwardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqQuestAward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务所属类型
     * </pre>
     *
     * <code>int32 questType = 1;</code>
     * @return The questType.
     */
    int getQuestType();

    /**
     * <pre>
     * 任务id（0表示一键领取）
     * </pre>
     *
     * <code>int32 questId = 2;</code>
     * @return The questId.
     */
    int getQuestId();
  }
  /**
   * <pre>
   * 请求任务领取奖励
   * </pre>
   *
   * Protobuf type {@code ReqQuestAward}
   */
  public static final class ReqQuestAward extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqQuestAward)
      ReqQuestAwardOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqQuestAward.class.getName());
    }
    // Use ReqQuestAward.newBuilder() to construct.
    private ReqQuestAward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqQuestAward() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.quest.proto.QuestProto.internal_static_ReqQuestAward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.quest.proto.QuestProto.internal_static_ReqQuestAward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.quest.proto.QuestProto.ReqQuestAward.class, com.game.quest.proto.QuestProto.ReqQuestAward.Builder.class);
    }

    /**
     * Protobuf enum {@code ReqQuestAward.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 110101;</code>
       */
      msgID(110101),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 110101;</code>
       */
      public static final int msgID_VALUE = 110101;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 110101: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.ReqQuestAward.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ReqQuestAward.E_MsgID)
    }

    public static final int QUESTTYPE_FIELD_NUMBER = 1;
    private int questType_ = 0;
    /**
     * <pre>
     * 任务所属类型
     * </pre>
     *
     * <code>int32 questType = 1;</code>
     * @return The questType.
     */
    @java.lang.Override
    public int getQuestType() {
      return questType_;
    }

    public static final int QUESTID_FIELD_NUMBER = 2;
    private int questId_ = 0;
    /**
     * <pre>
     * 任务id（0表示一键领取）
     * </pre>
     *
     * <code>int32 questId = 2;</code>
     * @return The questId.
     */
    @java.lang.Override
    public int getQuestId() {
      return questId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (questType_ != 0) {
        output.writeInt32(1, questType_);
      }
      if (questId_ != 0) {
        output.writeInt32(2, questId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (questType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, questType_);
      }
      if (questId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, questId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.quest.proto.QuestProto.ReqQuestAward)) {
        return super.equals(obj);
      }
      com.game.quest.proto.QuestProto.ReqQuestAward other = (com.game.quest.proto.QuestProto.ReqQuestAward) obj;

      if (getQuestType()
          != other.getQuestType()) return false;
      if (getQuestId()
          != other.getQuestId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getQuestType();
      hash = (37 * hash) + QUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getQuestId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.quest.proto.QuestProto.ReqQuestAward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.quest.proto.QuestProto.ReqQuestAward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ReqQuestAward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.quest.proto.QuestProto.ReqQuestAward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求任务领取奖励
     * </pre>
     *
     * Protobuf type {@code ReqQuestAward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqQuestAward)
        com.game.quest.proto.QuestProto.ReqQuestAwardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.internal_static_ReqQuestAward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.quest.proto.QuestProto.internal_static_ReqQuestAward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.quest.proto.QuestProto.ReqQuestAward.class, com.game.quest.proto.QuestProto.ReqQuestAward.Builder.class);
      }

      // Construct using com.game.quest.proto.QuestProto.ReqQuestAward.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        questType_ = 0;
        questId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.quest.proto.QuestProto.internal_static_ReqQuestAward_descriptor;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ReqQuestAward getDefaultInstanceForType() {
        return com.game.quest.proto.QuestProto.ReqQuestAward.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ReqQuestAward build() {
        com.game.quest.proto.QuestProto.ReqQuestAward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ReqQuestAward buildPartial() {
        com.game.quest.proto.QuestProto.ReqQuestAward result = new com.game.quest.proto.QuestProto.ReqQuestAward(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.game.quest.proto.QuestProto.ReqQuestAward result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.questType_ = questType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.questId_ = questId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.quest.proto.QuestProto.ReqQuestAward) {
          return mergeFrom((com.game.quest.proto.QuestProto.ReqQuestAward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.quest.proto.QuestProto.ReqQuestAward other) {
        if (other == com.game.quest.proto.QuestProto.ReqQuestAward.getDefaultInstance()) return this;
        if (other.getQuestType() != 0) {
          setQuestType(other.getQuestType());
        }
        if (other.getQuestId() != 0) {
          setQuestId(other.getQuestId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                questType_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                questId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int questType_ ;
      /**
       * <pre>
       * 任务所属类型
       * </pre>
       *
       * <code>int32 questType = 1;</code>
       * @return The questType.
       */
      @java.lang.Override
      public int getQuestType() {
        return questType_;
      }
      /**
       * <pre>
       * 任务所属类型
       * </pre>
       *
       * <code>int32 questType = 1;</code>
       * @param value The questType to set.
       * @return This builder for chaining.
       */
      public Builder setQuestType(int value) {

        questType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务所属类型
       * </pre>
       *
       * <code>int32 questType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        questType_ = 0;
        onChanged();
        return this;
      }

      private int questId_ ;
      /**
       * <pre>
       * 任务id（0表示一键领取）
       * </pre>
       *
       * <code>int32 questId = 2;</code>
       * @return The questId.
       */
      @java.lang.Override
      public int getQuestId() {
        return questId_;
      }
      /**
       * <pre>
       * 任务id（0表示一键领取）
       * </pre>
       *
       * <code>int32 questId = 2;</code>
       * @param value The questId to set.
       * @return This builder for chaining.
       */
      public Builder setQuestId(int value) {

        questId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id（0表示一键领取）
       * </pre>
       *
       * <code>int32 questId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        questId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqQuestAward)
    }

    // @@protoc_insertion_point(class_scope:ReqQuestAward)
    private static final com.game.quest.proto.QuestProto.ReqQuestAward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.quest.proto.QuestProto.ReqQuestAward();
    }

    public static com.game.quest.proto.QuestProto.ReqQuestAward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqQuestAward>
        PARSER = new com.google.protobuf.AbstractParser<ReqQuestAward>() {
      @java.lang.Override
      public ReqQuestAward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqQuestAward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqQuestAward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.quest.proto.QuestProto.ReqQuestAward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResQuestAwardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResQuestAward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @return A list containing the questId.
     */
    java.util.List<java.lang.Integer> getQuestIdList();
    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @return The count of questId.
     */
    int getQuestIdCount();
    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @param index The index of the element to return.
     * @return The questId at the given index.
     */
    int getQuestId(int index);

    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    java.util.List<com.game.bean.proto.BeanProto.ItemInfo> 
        getItemList();
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    com.game.bean.proto.BeanProto.ItemInfo getItem(int index);
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    int getItemCount();
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    java.util.List<? extends com.game.bean.proto.BeanProto.ItemInfoOrBuilder> 
        getItemOrBuilderList();
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    com.game.bean.proto.BeanProto.ItemInfoOrBuilder getItemOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回任务领取奖励
   * </pre>
   *
   * Protobuf type {@code ResQuestAward}
   */
  public static final class ResQuestAward extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResQuestAward)
      ResQuestAwardOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResQuestAward.class.getName());
    }
    // Use ResQuestAward.newBuilder() to construct.
    private ResQuestAward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResQuestAward() {
      questId_ = emptyIntList();
      item_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.quest.proto.QuestProto.internal_static_ResQuestAward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.quest.proto.QuestProto.internal_static_ResQuestAward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.quest.proto.QuestProto.ResQuestAward.class, com.game.quest.proto.QuestProto.ResQuestAward.Builder.class);
    }

    /**
     * Protobuf enum {@code ResQuestAward.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 110201;</code>
       */
      msgID(110201),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 110201;</code>
       */
      public static final int msgID_VALUE = 110201;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 110201: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.ResQuestAward.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResQuestAward.E_MsgID)
    }

    public static final int QUESTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList questId_ =
        emptyIntList();
    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @return A list containing the questId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getQuestIdList() {
      return questId_;
    }
    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @return The count of questId.
     */
    public int getQuestIdCount() {
      return questId_.size();
    }
    /**
     * <pre>
     * 领取的任务配置id列表
     * </pre>
     *
     * <code>repeated int32 questId = 1;</code>
     * @param index The index of the element to return.
     * @return The questId at the given index.
     */
    public int getQuestId(int index) {
      return questId_.getInt(index);
    }
    private int questIdMemoizedSerializedSize = -1;

    public static final int ITEM_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.game.bean.proto.BeanProto.ItemInfo> item_;
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.game.bean.proto.BeanProto.ItemInfo> getItemList() {
      return item_;
    }
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.game.bean.proto.BeanProto.ItemInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    @java.lang.Override
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.ItemInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <pre>
     * 奖励列表
     * </pre>
     *
     * <code>repeated .ItemInfo item = 2;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.ItemInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getQuestIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(questIdMemoizedSerializedSize);
      }
      for (int i = 0; i < questId_.size(); i++) {
        output.writeInt32NoTag(questId_.getInt(i));
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < questId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(questId_.getInt(i));
        }
        size += dataSize;
        if (!getQuestIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        questIdMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.quest.proto.QuestProto.ResQuestAward)) {
        return super.equals(obj);
      }
      com.game.quest.proto.QuestProto.ResQuestAward other = (com.game.quest.proto.QuestProto.ResQuestAward) obj;

      if (!getQuestIdList()
          .equals(other.getQuestIdList())) return false;
      if (!getItemList()
          .equals(other.getItemList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuestIdCount() > 0) {
        hash = (37 * hash) + QUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getQuestIdList().hashCode();
      }
      if (getItemCount() > 0) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItemList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.quest.proto.QuestProto.ResQuestAward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.quest.proto.QuestProto.ResQuestAward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ResQuestAward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.quest.proto.QuestProto.ResQuestAward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回任务领取奖励
     * </pre>
     *
     * Protobuf type {@code ResQuestAward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResQuestAward)
        com.game.quest.proto.QuestProto.ResQuestAwardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestAward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestAward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.quest.proto.QuestProto.ResQuestAward.class, com.game.quest.proto.QuestProto.ResQuestAward.Builder.class);
      }

      // Construct using com.game.quest.proto.QuestProto.ResQuestAward.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        questId_ = emptyIntList();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
        } else {
          item_ = null;
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestAward_descriptor;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestAward getDefaultInstanceForType() {
        return com.game.quest.proto.QuestProto.ResQuestAward.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestAward build() {
        com.game.quest.proto.QuestProto.ResQuestAward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestAward buildPartial() {
        com.game.quest.proto.QuestProto.ResQuestAward result = new com.game.quest.proto.QuestProto.ResQuestAward(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.game.quest.proto.QuestProto.ResQuestAward result) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
      }

      private void buildPartial0(com.game.quest.proto.QuestProto.ResQuestAward result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          questId_.makeImmutable();
          result.questId_ = questId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.quest.proto.QuestProto.ResQuestAward) {
          return mergeFrom((com.game.quest.proto.QuestProto.ResQuestAward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.quest.proto.QuestProto.ResQuestAward other) {
        if (other == com.game.quest.proto.QuestProto.ResQuestAward.getDefaultInstance()) return this;
        if (!other.questId_.isEmpty()) {
          if (questId_.isEmpty()) {
            questId_ = other.questId_;
            questId_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureQuestIdIsMutable();
            questId_.addAll(other.questId_);
          }
          onChanged();
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureQuestIdIsMutable();
                questId_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureQuestIdIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  questId_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 18: {
                com.game.bean.proto.BeanProto.ItemInfo m =
                    input.readMessage(
                        com.game.bean.proto.BeanProto.ItemInfo.parser(),
                        extensionRegistry);
                if (itemBuilder_ == null) {
                  ensureItemIsMutable();
                  item_.add(m);
                } else {
                  itemBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList questId_ = emptyIntList();
      private void ensureQuestIdIsMutable() {
        if (!questId_.isModifiable()) {
          questId_ = makeMutableCopy(questId_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @return A list containing the questId.
       */
      public java.util.List<java.lang.Integer>
          getQuestIdList() {
        questId_.makeImmutable();
        return questId_;
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @return The count of questId.
       */
      public int getQuestIdCount() {
        return questId_.size();
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @param index The index of the element to return.
       * @return The questId at the given index.
       */
      public int getQuestId(int index) {
        return questId_.getInt(index);
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @param index The index to set the value at.
       * @param value The questId to set.
       * @return This builder for chaining.
       */
      public Builder setQuestId(
          int index, int value) {

        ensureQuestIdIsMutable();
        questId_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @param value The questId to add.
       * @return This builder for chaining.
       */
      public Builder addQuestId(int value) {

        ensureQuestIdIsMutable();
        questId_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @param values The questId to add.
       * @return This builder for chaining.
       */
      public Builder addAllQuestId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureQuestIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, questId_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 领取的任务配置id列表
       * </pre>
       *
       * <code>repeated int32 questId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestId() {
        questId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<com.game.bean.proto.BeanProto.ItemInfo> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          item_ = new java.util.ArrayList<com.game.bean.proto.BeanProto.ItemInfo>(item_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.ItemInfo, com.game.bean.proto.BeanProto.ItemInfo.Builder, com.game.bean.proto.BeanProto.ItemInfoOrBuilder> itemBuilder_;

      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.ItemInfo> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public com.game.bean.proto.BeanProto.ItemInfo getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.game.bean.proto.BeanProto.ItemInfo value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder setItem(
          int index, com.game.bean.proto.BeanProto.ItemInfo.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder addItem(com.game.bean.proto.BeanProto.ItemInfo value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.game.bean.proto.BeanProto.ItemInfo value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder addItem(
          com.game.bean.proto.BeanProto.ItemInfo.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder addItem(
          int index, com.game.bean.proto.BeanProto.ItemInfo.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.game.bean.proto.BeanProto.ItemInfo> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public com.game.bean.proto.BeanProto.ItemInfo.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public com.game.bean.proto.BeanProto.ItemInfoOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public java.util.List<? extends com.game.bean.proto.BeanProto.ItemInfoOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public com.game.bean.proto.BeanProto.ItemInfo.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            com.game.bean.proto.BeanProto.ItemInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public com.game.bean.proto.BeanProto.ItemInfo.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, com.game.bean.proto.BeanProto.ItemInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 奖励列表
       * </pre>
       *
       * <code>repeated .ItemInfo item = 2;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.ItemInfo.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.ItemInfo, com.game.bean.proto.BeanProto.ItemInfo.Builder, com.game.bean.proto.BeanProto.ItemInfoOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.bean.proto.BeanProto.ItemInfo, com.game.bean.proto.BeanProto.ItemInfo.Builder, com.game.bean.proto.BeanProto.ItemInfoOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ResQuestAward)
    }

    // @@protoc_insertion_point(class_scope:ResQuestAward)
    private static final com.game.quest.proto.QuestProto.ResQuestAward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.quest.proto.QuestProto.ResQuestAward();
    }

    public static com.game.quest.proto.QuestProto.ResQuestAward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResQuestAward>
        PARSER = new com.google.protobuf.AbstractParser<ResQuestAward>() {
      @java.lang.Override
      public ResQuestAward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResQuestAward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResQuestAward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.quest.proto.QuestProto.ResQuestAward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResQuestUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResQuestUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    java.util.List<com.game.bean.proto.BeanProto.QuestInfo> 
        getQuestInfoList();
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    com.game.bean.proto.BeanProto.QuestInfo getQuestInfo(int index);
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    int getQuestInfoCount();
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    java.util.List<? extends com.game.bean.proto.BeanProto.QuestInfoOrBuilder> 
        getQuestInfoOrBuilderList();
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    com.game.bean.proto.BeanProto.QuestInfoOrBuilder getQuestInfoOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 返回任务进度更新（+新任务推送）
   * </pre>
   *
   * Protobuf type {@code ResQuestUpdate}
   */
  public static final class ResQuestUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResQuestUpdate)
      ResQuestUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResQuestUpdate.class.getName());
    }
    // Use ResQuestUpdate.newBuilder() to construct.
    private ResQuestUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResQuestUpdate() {
      questInfo_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.quest.proto.QuestProto.internal_static_ResQuestUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.quest.proto.QuestProto.internal_static_ResQuestUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.quest.proto.QuestProto.ResQuestUpdate.class, com.game.quest.proto.QuestProto.ResQuestUpdate.Builder.class);
    }

    /**
     * Protobuf enum {@code ResQuestUpdate.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 110202;</code>
       */
      msgID(110202),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 110202;</code>
       */
      public static final int msgID_VALUE = 110202;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 110202: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.ResQuestUpdate.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResQuestUpdate.E_MsgID)
    }

    public static final int QUESTINFO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.game.bean.proto.BeanProto.QuestInfo> questInfo_;
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.game.bean.proto.BeanProto.QuestInfo> getQuestInfoList() {
      return questInfo_;
    }
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.game.bean.proto.BeanProto.QuestInfoOrBuilder> 
        getQuestInfoOrBuilderList() {
      return questInfo_;
    }
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    @java.lang.Override
    public int getQuestInfoCount() {
      return questInfo_.size();
    }
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.QuestInfo getQuestInfo(int index) {
      return questInfo_.get(index);
    }
    /**
     * <pre>
     * 任务数据
     * </pre>
     *
     * <code>repeated .QuestInfo questInfo = 1;</code>
     */
    @java.lang.Override
    public com.game.bean.proto.BeanProto.QuestInfoOrBuilder getQuestInfoOrBuilder(
        int index) {
      return questInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < questInfo_.size(); i++) {
        output.writeMessage(1, questInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < questInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, questInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.quest.proto.QuestProto.ResQuestUpdate)) {
        return super.equals(obj);
      }
      com.game.quest.proto.QuestProto.ResQuestUpdate other = (com.game.quest.proto.QuestProto.ResQuestUpdate) obj;

      if (!getQuestInfoList()
          .equals(other.getQuestInfoList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuestInfoCount() > 0) {
        hash = (37 * hash) + QUESTINFO_FIELD_NUMBER;
        hash = (53 * hash) + getQuestInfoList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.quest.proto.QuestProto.ResQuestUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.quest.proto.QuestProto.ResQuestUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回任务进度更新（+新任务推送）
     * </pre>
     *
     * Protobuf type {@code ResQuestUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResQuestUpdate)
        com.game.quest.proto.QuestProto.ResQuestUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.quest.proto.QuestProto.ResQuestUpdate.class, com.game.quest.proto.QuestProto.ResQuestUpdate.Builder.class);
      }

      // Construct using com.game.quest.proto.QuestProto.ResQuestUpdate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (questInfoBuilder_ == null) {
          questInfo_ = java.util.Collections.emptyList();
        } else {
          questInfo_ = null;
          questInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.quest.proto.QuestProto.internal_static_ResQuestUpdate_descriptor;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestUpdate getDefaultInstanceForType() {
        return com.game.quest.proto.QuestProto.ResQuestUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestUpdate build() {
        com.game.quest.proto.QuestProto.ResQuestUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.quest.proto.QuestProto.ResQuestUpdate buildPartial() {
        com.game.quest.proto.QuestProto.ResQuestUpdate result = new com.game.quest.proto.QuestProto.ResQuestUpdate(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.game.quest.proto.QuestProto.ResQuestUpdate result) {
        if (questInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            questInfo_ = java.util.Collections.unmodifiableList(questInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.questInfo_ = questInfo_;
        } else {
          result.questInfo_ = questInfoBuilder_.build();
        }
      }

      private void buildPartial0(com.game.quest.proto.QuestProto.ResQuestUpdate result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.quest.proto.QuestProto.ResQuestUpdate) {
          return mergeFrom((com.game.quest.proto.QuestProto.ResQuestUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.quest.proto.QuestProto.ResQuestUpdate other) {
        if (other == com.game.quest.proto.QuestProto.ResQuestUpdate.getDefaultInstance()) return this;
        if (questInfoBuilder_ == null) {
          if (!other.questInfo_.isEmpty()) {
            if (questInfo_.isEmpty()) {
              questInfo_ = other.questInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuestInfoIsMutable();
              questInfo_.addAll(other.questInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.questInfo_.isEmpty()) {
            if (questInfoBuilder_.isEmpty()) {
              questInfoBuilder_.dispose();
              questInfoBuilder_ = null;
              questInfo_ = other.questInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              questInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getQuestInfoFieldBuilder() : null;
            } else {
              questInfoBuilder_.addAllMessages(other.questInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.game.bean.proto.BeanProto.QuestInfo m =
                    input.readMessage(
                        com.game.bean.proto.BeanProto.QuestInfo.parser(),
                        extensionRegistry);
                if (questInfoBuilder_ == null) {
                  ensureQuestInfoIsMutable();
                  questInfo_.add(m);
                } else {
                  questInfoBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.bean.proto.BeanProto.QuestInfo> questInfo_ =
        java.util.Collections.emptyList();
      private void ensureQuestInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          questInfo_ = new java.util.ArrayList<com.game.bean.proto.BeanProto.QuestInfo>(questInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.QuestInfo, com.game.bean.proto.BeanProto.QuestInfo.Builder, com.game.bean.proto.BeanProto.QuestInfoOrBuilder> questInfoBuilder_;

      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.QuestInfo> getQuestInfoList() {
        if (questInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(questInfo_);
        } else {
          return questInfoBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public int getQuestInfoCount() {
        if (questInfoBuilder_ == null) {
          return questInfo_.size();
        } else {
          return questInfoBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.QuestInfo getQuestInfo(int index) {
        if (questInfoBuilder_ == null) {
          return questInfo_.get(index);
        } else {
          return questInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder setQuestInfo(
          int index, com.game.bean.proto.BeanProto.QuestInfo value) {
        if (questInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestInfoIsMutable();
          questInfo_.set(index, value);
          onChanged();
        } else {
          questInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder setQuestInfo(
          int index, com.game.bean.proto.BeanProto.QuestInfo.Builder builderForValue) {
        if (questInfoBuilder_ == null) {
          ensureQuestInfoIsMutable();
          questInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          questInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder addQuestInfo(com.game.bean.proto.BeanProto.QuestInfo value) {
        if (questInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestInfoIsMutable();
          questInfo_.add(value);
          onChanged();
        } else {
          questInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder addQuestInfo(
          int index, com.game.bean.proto.BeanProto.QuestInfo value) {
        if (questInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestInfoIsMutable();
          questInfo_.add(index, value);
          onChanged();
        } else {
          questInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder addQuestInfo(
          com.game.bean.proto.BeanProto.QuestInfo.Builder builderForValue) {
        if (questInfoBuilder_ == null) {
          ensureQuestInfoIsMutable();
          questInfo_.add(builderForValue.build());
          onChanged();
        } else {
          questInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder addQuestInfo(
          int index, com.game.bean.proto.BeanProto.QuestInfo.Builder builderForValue) {
        if (questInfoBuilder_ == null) {
          ensureQuestInfoIsMutable();
          questInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          questInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder addAllQuestInfo(
          java.lang.Iterable<? extends com.game.bean.proto.BeanProto.QuestInfo> values) {
        if (questInfoBuilder_ == null) {
          ensureQuestInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, questInfo_);
          onChanged();
        } else {
          questInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder clearQuestInfo() {
        if (questInfoBuilder_ == null) {
          questInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          questInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public Builder removeQuestInfo(int index) {
        if (questInfoBuilder_ == null) {
          ensureQuestInfoIsMutable();
          questInfo_.remove(index);
          onChanged();
        } else {
          questInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.QuestInfo.Builder getQuestInfoBuilder(
          int index) {
        return getQuestInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.QuestInfoOrBuilder getQuestInfoOrBuilder(
          int index) {
        if (questInfoBuilder_ == null) {
          return questInfo_.get(index);  } else {
          return questInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public java.util.List<? extends com.game.bean.proto.BeanProto.QuestInfoOrBuilder> 
           getQuestInfoOrBuilderList() {
        if (questInfoBuilder_ != null) {
          return questInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(questInfo_);
        }
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.QuestInfo.Builder addQuestInfoBuilder() {
        return getQuestInfoFieldBuilder().addBuilder(
            com.game.bean.proto.BeanProto.QuestInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public com.game.bean.proto.BeanProto.QuestInfo.Builder addQuestInfoBuilder(
          int index) {
        return getQuestInfoFieldBuilder().addBuilder(
            index, com.game.bean.proto.BeanProto.QuestInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 任务数据
       * </pre>
       *
       * <code>repeated .QuestInfo questInfo = 1;</code>
       */
      public java.util.List<com.game.bean.proto.BeanProto.QuestInfo.Builder> 
           getQuestInfoBuilderList() {
        return getQuestInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.bean.proto.BeanProto.QuestInfo, com.game.bean.proto.BeanProto.QuestInfo.Builder, com.game.bean.proto.BeanProto.QuestInfoOrBuilder> 
          getQuestInfoFieldBuilder() {
        if (questInfoBuilder_ == null) {
          questInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.bean.proto.BeanProto.QuestInfo, com.game.bean.proto.BeanProto.QuestInfo.Builder, com.game.bean.proto.BeanProto.QuestInfoOrBuilder>(
                  questInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          questInfo_ = null;
        }
        return questInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ResQuestUpdate)
    }

    // @@protoc_insertion_point(class_scope:ResQuestUpdate)
    private static final com.game.quest.proto.QuestProto.ResQuestUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.quest.proto.QuestProto.ResQuestUpdate();
    }

    public static com.game.quest.proto.QuestProto.ResQuestUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResQuestUpdate>
        PARSER = new com.google.protobuf.AbstractParser<ResQuestUpdate>() {
      @java.lang.Override
      public ResQuestUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResQuestUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResQuestUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.quest.proto.QuestProto.ResQuestUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqQuestAward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqQuestAward_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResQuestAward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResQuestAward_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResQuestUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResQuestUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022questMessage.proto\032\nbean.proto\"T\n\rReqQ" +
      "uestAward\022\021\n\tquestType\030\001 \001(\005\022\017\n\007questId\030" +
      "\002 \001(\005\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n\005msgID\020\225\334\006\"Z" +
      "\n\rResQuestAward\022\017\n\007questId\030\001 \003(\005\022\027\n\004item" +
      "\030\002 \003(\0132\t.ItemInfo\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n" +
      "\005msgID\020\371\334\006\"P\n\016ResQuestUpdate\022\035\n\tquestInf" +
      "o\030\001 \003(\0132\n.QuestInfo\"\037\n\007E_MsgID\022\007\n\003def\020\000\022" +
      "\013\n\005msgID\020\372\334\006B\"\n\024com.game.quest.protoB\nQu" +
      "estProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.bean.proto.BeanProto.getDescriptor(),
        });
    internal_static_ReqQuestAward_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqQuestAward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqQuestAward_descriptor,
        new java.lang.String[] { "QuestType", "QuestId", });
    internal_static_ResQuestAward_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResQuestAward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResQuestAward_descriptor,
        new java.lang.String[] { "QuestId", "Item", });
    internal_static_ResQuestUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResQuestUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResQuestUpdate_descriptor,
        new java.lang.String[] { "QuestInfo", });
    descriptor.resolveAllFeaturesImmutable();
    com.game.bean.proto.BeanProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
