// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: towerMessage.proto
// Protobuf Java Version: 4.26.1

package com.game.tower.proto;

public final class TowerProto {
  private TowerProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TowerProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqTowerBuffChooseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqTowerBuffChoose)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 请求buff选择
   * </pre>
   *
   * Protobuf type {@code ReqTowerBuffChoose}
   */
  public static final class ReqTowerBuffChoose extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqTowerBuffChoose)
      ReqTowerBuffChooseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqTowerBuffChoose.class.getName());
    }
    // Use ReqTowerBuffChoose.newBuilder() to construct.
    private ReqTowerBuffChoose(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqTowerBuffChoose() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.tower.proto.TowerProto.internal_static_ReqTowerBuffChoose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.tower.proto.TowerProto.internal_static_ReqTowerBuffChoose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.tower.proto.TowerProto.ReqTowerBuffChoose.class, com.game.tower.proto.TowerProto.ReqTowerBuffChoose.Builder.class);
    }

    /**
     * Protobuf enum {@code ReqTowerBuffChoose.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 122102;</code>
       */
      msgID(122102),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 122102;</code>
       */
      public static final int msgID_VALUE = 122102;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 122102: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.ReqTowerBuffChoose.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ReqTowerBuffChoose.E_MsgID)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.tower.proto.TowerProto.ReqTowerBuffChoose)) {
        return super.equals(obj);
      }
      com.game.tower.proto.TowerProto.ReqTowerBuffChoose other = (com.game.tower.proto.TowerProto.ReqTowerBuffChoose) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.tower.proto.TowerProto.ReqTowerBuffChoose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求buff选择
     * </pre>
     *
     * Protobuf type {@code ReqTowerBuffChoose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqTowerBuffChoose)
        com.game.tower.proto.TowerProto.ReqTowerBuffChooseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerBuffChoose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerBuffChoose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.tower.proto.TowerProto.ReqTowerBuffChoose.class, com.game.tower.proto.TowerProto.ReqTowerBuffChoose.Builder.class);
      }

      // Construct using com.game.tower.proto.TowerProto.ReqTowerBuffChoose.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerBuffChoose_descriptor;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerBuffChoose getDefaultInstanceForType() {
        return com.game.tower.proto.TowerProto.ReqTowerBuffChoose.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerBuffChoose build() {
        com.game.tower.proto.TowerProto.ReqTowerBuffChoose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerBuffChoose buildPartial() {
        com.game.tower.proto.TowerProto.ReqTowerBuffChoose result = new com.game.tower.proto.TowerProto.ReqTowerBuffChoose(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.tower.proto.TowerProto.ReqTowerBuffChoose) {
          return mergeFrom((com.game.tower.proto.TowerProto.ReqTowerBuffChoose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.tower.proto.TowerProto.ReqTowerBuffChoose other) {
        if (other == com.game.tower.proto.TowerProto.ReqTowerBuffChoose.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqTowerBuffChoose)
    }

    // @@protoc_insertion_point(class_scope:ReqTowerBuffChoose)
    private static final com.game.tower.proto.TowerProto.ReqTowerBuffChoose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.tower.proto.TowerProto.ReqTowerBuffChoose();
    }

    public static com.game.tower.proto.TowerProto.ReqTowerBuffChoose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqTowerBuffChoose>
        PARSER = new com.google.protobuf.AbstractParser<ReqTowerBuffChoose>() {
      @java.lang.Override
      public ReqTowerBuffChoose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqTowerBuffChoose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqTowerBuffChoose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.tower.proto.TowerProto.ReqTowerBuffChoose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResTowerBuffChooseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResTowerBuffChoose)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 返回buff选择
   * </pre>
   *
   * Protobuf type {@code ResTowerBuffChoose}
   */
  public static final class ResTowerBuffChoose extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResTowerBuffChoose)
      ResTowerBuffChooseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResTowerBuffChoose.class.getName());
    }
    // Use ResTowerBuffChoose.newBuilder() to construct.
    private ResTowerBuffChoose(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResTowerBuffChoose() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.tower.proto.TowerProto.internal_static_ResTowerBuffChoose_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.tower.proto.TowerProto.internal_static_ResTowerBuffChoose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.tower.proto.TowerProto.ResTowerBuffChoose.class, com.game.tower.proto.TowerProto.ResTowerBuffChoose.Builder.class);
    }

    /**
     * Protobuf enum {@code ResTowerBuffChoose.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 122202;</code>
       */
      msgID(122202),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 122202;</code>
       */
      public static final int msgID_VALUE = 122202;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 122202: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.ResTowerBuffChoose.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResTowerBuffChoose.E_MsgID)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.tower.proto.TowerProto.ResTowerBuffChoose)) {
        return super.equals(obj);
      }
      com.game.tower.proto.TowerProto.ResTowerBuffChoose other = (com.game.tower.proto.TowerProto.ResTowerBuffChoose) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.tower.proto.TowerProto.ResTowerBuffChoose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回buff选择
     * </pre>
     *
     * Protobuf type {@code ResTowerBuffChoose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResTowerBuffChoose)
        com.game.tower.proto.TowerProto.ResTowerBuffChooseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerBuffChoose_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerBuffChoose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.tower.proto.TowerProto.ResTowerBuffChoose.class, com.game.tower.proto.TowerProto.ResTowerBuffChoose.Builder.class);
      }

      // Construct using com.game.tower.proto.TowerProto.ResTowerBuffChoose.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerBuffChoose_descriptor;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerBuffChoose getDefaultInstanceForType() {
        return com.game.tower.proto.TowerProto.ResTowerBuffChoose.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerBuffChoose build() {
        com.game.tower.proto.TowerProto.ResTowerBuffChoose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerBuffChoose buildPartial() {
        com.game.tower.proto.TowerProto.ResTowerBuffChoose result = new com.game.tower.proto.TowerProto.ResTowerBuffChoose(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.tower.proto.TowerProto.ResTowerBuffChoose) {
          return mergeFrom((com.game.tower.proto.TowerProto.ResTowerBuffChoose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.tower.proto.TowerProto.ResTowerBuffChoose other) {
        if (other == com.game.tower.proto.TowerProto.ResTowerBuffChoose.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResTowerBuffChoose)
    }

    // @@protoc_insertion_point(class_scope:ResTowerBuffChoose)
    private static final com.game.tower.proto.TowerProto.ResTowerBuffChoose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.tower.proto.TowerProto.ResTowerBuffChoose();
    }

    public static com.game.tower.proto.TowerProto.ResTowerBuffChoose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResTowerBuffChoose>
        PARSER = new com.google.protobuf.AbstractParser<ResTowerBuffChoose>() {
      @java.lang.Override
      public ResTowerBuffChoose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResTowerBuffChoose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResTowerBuffChoose> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.tower.proto.TowerProto.ResTowerBuffChoose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqTowerStageRewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqTowerStageReward)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 请求层数奖励
   * </pre>
   *
   * Protobuf type {@code ReqTowerStageReward}
   */
  public static final class ReqTowerStageReward extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqTowerStageReward)
      ReqTowerStageRewardOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqTowerStageReward.class.getName());
    }
    // Use ReqTowerStageReward.newBuilder() to construct.
    private ReqTowerStageReward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqTowerStageReward() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.tower.proto.TowerProto.internal_static_ReqTowerStageReward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.tower.proto.TowerProto.internal_static_ReqTowerStageReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.tower.proto.TowerProto.ReqTowerStageReward.class, com.game.tower.proto.TowerProto.ReqTowerStageReward.Builder.class);
    }

    /**
     * Protobuf enum {@code ReqTowerStageReward.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 122103;</code>
       */
      msgID(122103),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 122103;</code>
       */
      public static final int msgID_VALUE = 122103;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 122103: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.ReqTowerStageReward.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ReqTowerStageReward.E_MsgID)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.tower.proto.TowerProto.ReqTowerStageReward)) {
        return super.equals(obj);
      }
      com.game.tower.proto.TowerProto.ReqTowerStageReward other = (com.game.tower.proto.TowerProto.ReqTowerStageReward) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ReqTowerStageReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.tower.proto.TowerProto.ReqTowerStageReward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求层数奖励
     * </pre>
     *
     * Protobuf type {@code ReqTowerStageReward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqTowerStageReward)
        com.game.tower.proto.TowerProto.ReqTowerStageRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerStageReward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerStageReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.tower.proto.TowerProto.ReqTowerStageReward.class, com.game.tower.proto.TowerProto.ReqTowerStageReward.Builder.class);
      }

      // Construct using com.game.tower.proto.TowerProto.ReqTowerStageReward.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.tower.proto.TowerProto.internal_static_ReqTowerStageReward_descriptor;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerStageReward getDefaultInstanceForType() {
        return com.game.tower.proto.TowerProto.ReqTowerStageReward.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerStageReward build() {
        com.game.tower.proto.TowerProto.ReqTowerStageReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ReqTowerStageReward buildPartial() {
        com.game.tower.proto.TowerProto.ReqTowerStageReward result = new com.game.tower.proto.TowerProto.ReqTowerStageReward(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.tower.proto.TowerProto.ReqTowerStageReward) {
          return mergeFrom((com.game.tower.proto.TowerProto.ReqTowerStageReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.tower.proto.TowerProto.ReqTowerStageReward other) {
        if (other == com.game.tower.proto.TowerProto.ReqTowerStageReward.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqTowerStageReward)
    }

    // @@protoc_insertion_point(class_scope:ReqTowerStageReward)
    private static final com.game.tower.proto.TowerProto.ReqTowerStageReward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.tower.proto.TowerProto.ReqTowerStageReward();
    }

    public static com.game.tower.proto.TowerProto.ReqTowerStageReward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqTowerStageReward>
        PARSER = new com.google.protobuf.AbstractParser<ReqTowerStageReward>() {
      @java.lang.Override
      public ReqTowerStageReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqTowerStageReward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqTowerStageReward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.tower.proto.TowerProto.ReqTowerStageReward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResTowerStageRewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResTowerStageReward)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 返回层数奖励
   * </pre>
   *
   * Protobuf type {@code ResTowerStageReward}
   */
  public static final class ResTowerStageReward extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResTowerStageReward)
      ResTowerStageRewardOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResTowerStageReward.class.getName());
    }
    // Use ResTowerStageReward.newBuilder() to construct.
    private ResTowerStageReward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResTowerStageReward() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.tower.proto.TowerProto.internal_static_ResTowerStageReward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.tower.proto.TowerProto.internal_static_ResTowerStageReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.tower.proto.TowerProto.ResTowerStageReward.class, com.game.tower.proto.TowerProto.ResTowerStageReward.Builder.class);
    }

    /**
     * Protobuf enum {@code ResTowerStageReward.E_MsgID}
     */
    public enum E_MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>def = 0;</code>
       */
      def(0),
      /**
       * <code>msgID = 122203;</code>
       */
      msgID(122203),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          E_MsgID.class.getName());
      }
      /**
       * <code>def = 0;</code>
       */
      public static final int def_VALUE = 0;
      /**
       * <code>msgID = 122203;</code>
       */
      public static final int msgID_VALUE = 122203;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E_MsgID valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E_MsgID forNumber(int value) {
        switch (value) {
          case 0: return def;
          case 122203: return msgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E_MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E_MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E_MsgID>() {
              public E_MsgID findValueByNumber(int number) {
                return E_MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.ResTowerStageReward.getDescriptor().getEnumTypes().get(0);
      }

      private static final E_MsgID[] VALUES = values();

      public static E_MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E_MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResTowerStageReward.E_MsgID)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.tower.proto.TowerProto.ResTowerStageReward)) {
        return super.equals(obj);
      }
      com.game.tower.proto.TowerProto.ResTowerStageReward other = (com.game.tower.proto.TowerProto.ResTowerStageReward) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.tower.proto.TowerProto.ResTowerStageReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.tower.proto.TowerProto.ResTowerStageReward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回层数奖励
     * </pre>
     *
     * Protobuf type {@code ResTowerStageReward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResTowerStageReward)
        com.game.tower.proto.TowerProto.ResTowerStageRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerStageReward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerStageReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.tower.proto.TowerProto.ResTowerStageReward.class, com.game.tower.proto.TowerProto.ResTowerStageReward.Builder.class);
      }

      // Construct using com.game.tower.proto.TowerProto.ResTowerStageReward.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.tower.proto.TowerProto.internal_static_ResTowerStageReward_descriptor;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerStageReward getDefaultInstanceForType() {
        return com.game.tower.proto.TowerProto.ResTowerStageReward.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerStageReward build() {
        com.game.tower.proto.TowerProto.ResTowerStageReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.tower.proto.TowerProto.ResTowerStageReward buildPartial() {
        com.game.tower.proto.TowerProto.ResTowerStageReward result = new com.game.tower.proto.TowerProto.ResTowerStageReward(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.tower.proto.TowerProto.ResTowerStageReward) {
          return mergeFrom((com.game.tower.proto.TowerProto.ResTowerStageReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.tower.proto.TowerProto.ResTowerStageReward other) {
        if (other == com.game.tower.proto.TowerProto.ResTowerStageReward.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResTowerStageReward)
    }

    // @@protoc_insertion_point(class_scope:ResTowerStageReward)
    private static final com.game.tower.proto.TowerProto.ResTowerStageReward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.tower.proto.TowerProto.ResTowerStageReward();
    }

    public static com.game.tower.proto.TowerProto.ResTowerStageReward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResTowerStageReward>
        PARSER = new com.google.protobuf.AbstractParser<ResTowerStageReward>() {
      @java.lang.Override
      public ResTowerStageReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResTowerStageReward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResTowerStageReward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.tower.proto.TowerProto.ResTowerStageReward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqTowerBuffChoose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqTowerBuffChoose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResTowerBuffChoose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResTowerBuffChoose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqTowerStageReward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqTowerStageReward_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResTowerStageReward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResTowerStageReward_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022towerMessage.proto\"5\n\022ReqTowerBuffChoo" +
      "se\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n\005msgID\020\366\271\007\"5\n\022R" +
      "esTowerBuffChoose\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n" +
      "\005msgID\020\332\272\007\"6\n\023ReqTowerStageReward\"\037\n\007E_M" +
      "sgID\022\007\n\003def\020\000\022\013\n\005msgID\020\367\271\007\"6\n\023ResTowerSt" +
      "ageReward\"\037\n\007E_MsgID\022\007\n\003def\020\000\022\013\n\005msgID\020\333" +
      "\272\007B\"\n\024com.game.tower.protoB\nTowerProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReqTowerBuffChoose_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqTowerBuffChoose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqTowerBuffChoose_descriptor,
        new java.lang.String[] { });
    internal_static_ResTowerBuffChoose_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResTowerBuffChoose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResTowerBuffChoose_descriptor,
        new java.lang.String[] { });
    internal_static_ReqTowerStageReward_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReqTowerStageReward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqTowerStageReward_descriptor,
        new java.lang.String[] { });
    internal_static_ResTowerStageReward_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResTowerStageReward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResTowerStageReward_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
