// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publicGateMessage.proto
// Protobuf Java Version: 4.26.1

package com.game.gate.proto;

public final class GateProto {
  private GateProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      GateProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Gate2ServerServerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Gate2ServerServerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 serverId = 1;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <pre>
     * 服务器名称
     * </pre>
     *
     * <code>string serverName = 2;</code>
     * @return The serverName.
     */
    java.lang.String getServerName();
    /**
     * <pre>
     * 服务器名称
     * </pre>
     *
     * <code>string serverName = 2;</code>
     * @return The bytes for serverName.
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <pre>
     * 服务器开服时间
     * </pre>
     *
     * <code>fixed64 serverOpenTime = 3;</code>
     * @return The serverOpenTime.
     */
    long getServerOpenTime();
  }
  /**
   * <pre>
   * -------------------------------------Bean-------------------------------------
   * 服务器信息Bean（网关和服务器通信用）
   * </pre>
   *
   * Protobuf type {@code Gate2ServerServerInfo}
   */
  public static final class Gate2ServerServerInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Gate2ServerServerInfo)
      Gate2ServerServerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Gate2ServerServerInfo.class.getName());
    }
    // Use Gate2ServerServerInfo.newBuilder() to construct.
    private Gate2ServerServerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Gate2ServerServerInfo() {
      serverName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.gate.proto.GateProto.internal_static_Gate2ServerServerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.gate.proto.GateProto.internal_static_Gate2ServerServerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.gate.proto.GateProto.Gate2ServerServerInfo.class, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_ = 0;
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 serverId = 1;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int SERVERNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverName_ = "";
    /**
     * <pre>
     * 服务器名称
     * </pre>
     *
     * <code>string serverName = 2;</code>
     * @return The serverName.
     */
    @java.lang.Override
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 服务器名称
     * </pre>
     *
     * <code>string serverName = 2;</code>
     * @return The bytes for serverName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVEROPENTIME_FIELD_NUMBER = 3;
    private long serverOpenTime_ = 0L;
    /**
     * <pre>
     * 服务器开服时间
     * </pre>
     *
     * <code>fixed64 serverOpenTime = 3;</code>
     * @return The serverOpenTime.
     */
    @java.lang.Override
    public long getServerOpenTime() {
      return serverOpenTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeInt32(1, serverId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, serverName_);
      }
      if (serverOpenTime_ != 0L) {
        output.writeFixed64(3, serverOpenTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, serverName_);
      }
      if (serverOpenTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, serverOpenTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.gate.proto.GateProto.Gate2ServerServerInfo)) {
        return super.equals(obj);
      }
      com.game.gate.proto.GateProto.Gate2ServerServerInfo other = (com.game.gate.proto.GateProto.Gate2ServerServerInfo) obj;

      if (getServerId()
          != other.getServerId()) return false;
      if (!getServerName()
          .equals(other.getServerName())) return false;
      if (getServerOpenTime()
          != other.getServerOpenTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getServerName().hashCode();
      hash = (37 * hash) + SERVEROPENTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerOpenTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.gate.proto.GateProto.Gate2ServerServerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * -------------------------------------Bean-------------------------------------
     * 服务器信息Bean（网关和服务器通信用）
     * </pre>
     *
     * Protobuf type {@code Gate2ServerServerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Gate2ServerServerInfo)
        com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.gate.proto.GateProto.internal_static_Gate2ServerServerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.gate.proto.GateProto.internal_static_Gate2ServerServerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.gate.proto.GateProto.Gate2ServerServerInfo.class, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder.class);
      }

      // Construct using com.game.gate.proto.GateProto.Gate2ServerServerInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverId_ = 0;
        serverName_ = "";
        serverOpenTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.gate.proto.GateProto.internal_static_Gate2ServerServerInfo_descriptor;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo getDefaultInstanceForType() {
        return com.game.gate.proto.GateProto.Gate2ServerServerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo build() {
        com.game.gate.proto.GateProto.Gate2ServerServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo buildPartial() {
        com.game.gate.proto.GateProto.Gate2ServerServerInfo result = new com.game.gate.proto.GateProto.Gate2ServerServerInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.game.gate.proto.GateProto.Gate2ServerServerInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverId_ = serverId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serverName_ = serverName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.serverOpenTime_ = serverOpenTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.gate.proto.GateProto.Gate2ServerServerInfo) {
          return mergeFrom((com.game.gate.proto.GateProto.Gate2ServerServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.gate.proto.GateProto.Gate2ServerServerInfo other) {
        if (other == com.game.gate.proto.GateProto.Gate2ServerServerInfo.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (!other.getServerName().isEmpty()) {
          serverName_ = other.serverName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getServerOpenTime() != 0L) {
          setServerOpenTime(other.getServerOpenTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                serverName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                serverOpenTime_ = input.readFixed64();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 serverId = 1;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 serverId = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 serverId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serverName_ = "";
      /**
       * <pre>
       * 服务器名称
       * </pre>
       *
       * <code>string serverName = 2;</code>
       * @return The serverName.
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 服务器名称
       * </pre>
       *
       * <code>string serverName = 2;</code>
       * @return The bytes for serverName.
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 服务器名称
       * </pre>
       *
       * <code>string serverName = 2;</code>
       * @param value The serverName to set.
       * @return This builder for chaining.
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serverName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器名称
       * </pre>
       *
       * <code>string serverName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerName() {
        serverName_ = getDefaultInstance().getServerName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器名称
       * </pre>
       *
       * <code>string serverName = 2;</code>
       * @param value The bytes for serverName to set.
       * @return This builder for chaining.
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serverName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long serverOpenTime_ ;
      /**
       * <pre>
       * 服务器开服时间
       * </pre>
       *
       * <code>fixed64 serverOpenTime = 3;</code>
       * @return The serverOpenTime.
       */
      @java.lang.Override
      public long getServerOpenTime() {
        return serverOpenTime_;
      }
      /**
       * <pre>
       * 服务器开服时间
       * </pre>
       *
       * <code>fixed64 serverOpenTime = 3;</code>
       * @param value The serverOpenTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerOpenTime(long value) {

        serverOpenTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器开服时间
       * </pre>
       *
       * <code>fixed64 serverOpenTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerOpenTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverOpenTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Gate2ServerServerInfo)
    }

    // @@protoc_insertion_point(class_scope:Gate2ServerServerInfo)
    private static final com.game.gate.proto.GateProto.Gate2ServerServerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.gate.proto.GateProto.Gate2ServerServerInfo();
    }

    public static com.game.gate.proto.GateProto.Gate2ServerServerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Gate2ServerServerInfo>
        PARSER = new com.google.protobuf.AbstractParser<Gate2ServerServerInfo>() {
      @java.lang.Override
      public Gate2ServerServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Gate2ServerServerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Gate2ServerServerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.gate.proto.GateProto.Gate2ServerServerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqPublicRegisterServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqPublicRegisterServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo> 
        getServerInfoListList();
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    com.game.gate.proto.GateProto.Gate2ServerServerInfo getServerInfoList(int index);
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    int getServerInfoListCount();
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    java.util.List<? extends com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder> 
        getServerInfoListOrBuilderList();
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder getServerInfoListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 请求向网关注册服务器信息 msgId=201101 返回登录消息msgId=201201
   * </pre>
   *
   * Protobuf type {@code ReqPublicRegisterServer}
   */
  public static final class ReqPublicRegisterServer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqPublicRegisterServer)
      ReqPublicRegisterServerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqPublicRegisterServer.class.getName());
    }
    // Use ReqPublicRegisterServer.newBuilder() to construct.
    private ReqPublicRegisterServer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqPublicRegisterServer() {
      serverInfoList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.gate.proto.GateProto.internal_static_ReqPublicRegisterServer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.gate.proto.GateProto.internal_static_ReqPublicRegisterServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.gate.proto.GateProto.ReqPublicRegisterServer.class, com.game.gate.proto.GateProto.ReqPublicRegisterServer.Builder.class);
    }

    public static final int SERVERINFOLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo> serverInfoList_;
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo> getServerInfoListList() {
      return serverInfoList_;
    }
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder> 
        getServerInfoListOrBuilderList() {
      return serverInfoList_;
    }
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    @java.lang.Override
    public int getServerInfoListCount() {
      return serverInfoList_.size();
    }
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    @java.lang.Override
    public com.game.gate.proto.GateProto.Gate2ServerServerInfo getServerInfoList(int index) {
      return serverInfoList_.get(index);
    }
    /**
     * <pre>
     * 服务器信息
     * </pre>
     *
     * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
     */
    @java.lang.Override
    public com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder getServerInfoListOrBuilder(
        int index) {
      return serverInfoList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < serverInfoList_.size(); i++) {
        output.writeMessage(1, serverInfoList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < serverInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, serverInfoList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.gate.proto.GateProto.ReqPublicRegisterServer)) {
        return super.equals(obj);
      }
      com.game.gate.proto.GateProto.ReqPublicRegisterServer other = (com.game.gate.proto.GateProto.ReqPublicRegisterServer) obj;

      if (!getServerInfoListList()
          .equals(other.getServerInfoListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getServerInfoListCount() > 0) {
        hash = (37 * hash) + SERVERINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getServerInfoListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.gate.proto.GateProto.ReqPublicRegisterServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求向网关注册服务器信息 msgId=201101 返回登录消息msgId=201201
     * </pre>
     *
     * Protobuf type {@code ReqPublicRegisterServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqPublicRegisterServer)
        com.game.gate.proto.GateProto.ReqPublicRegisterServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.gate.proto.GateProto.internal_static_ReqPublicRegisterServer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.gate.proto.GateProto.internal_static_ReqPublicRegisterServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.gate.proto.GateProto.ReqPublicRegisterServer.class, com.game.gate.proto.GateProto.ReqPublicRegisterServer.Builder.class);
      }

      // Construct using com.game.gate.proto.GateProto.ReqPublicRegisterServer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (serverInfoListBuilder_ == null) {
          serverInfoList_ = java.util.Collections.emptyList();
        } else {
          serverInfoList_ = null;
          serverInfoListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.gate.proto.GateProto.internal_static_ReqPublicRegisterServer_descriptor;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ReqPublicRegisterServer getDefaultInstanceForType() {
        return com.game.gate.proto.GateProto.ReqPublicRegisterServer.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ReqPublicRegisterServer build() {
        com.game.gate.proto.GateProto.ReqPublicRegisterServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ReqPublicRegisterServer buildPartial() {
        com.game.gate.proto.GateProto.ReqPublicRegisterServer result = new com.game.gate.proto.GateProto.ReqPublicRegisterServer(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.game.gate.proto.GateProto.ReqPublicRegisterServer result) {
        if (serverInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            serverInfoList_ = java.util.Collections.unmodifiableList(serverInfoList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.serverInfoList_ = serverInfoList_;
        } else {
          result.serverInfoList_ = serverInfoListBuilder_.build();
        }
      }

      private void buildPartial0(com.game.gate.proto.GateProto.ReqPublicRegisterServer result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.gate.proto.GateProto.ReqPublicRegisterServer) {
          return mergeFrom((com.game.gate.proto.GateProto.ReqPublicRegisterServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.gate.proto.GateProto.ReqPublicRegisterServer other) {
        if (other == com.game.gate.proto.GateProto.ReqPublicRegisterServer.getDefaultInstance()) return this;
        if (serverInfoListBuilder_ == null) {
          if (!other.serverInfoList_.isEmpty()) {
            if (serverInfoList_.isEmpty()) {
              serverInfoList_ = other.serverInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureServerInfoListIsMutable();
              serverInfoList_.addAll(other.serverInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.serverInfoList_.isEmpty()) {
            if (serverInfoListBuilder_.isEmpty()) {
              serverInfoListBuilder_.dispose();
              serverInfoListBuilder_ = null;
              serverInfoList_ = other.serverInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              serverInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getServerInfoListFieldBuilder() : null;
            } else {
              serverInfoListBuilder_.addAllMessages(other.serverInfoList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.game.gate.proto.GateProto.Gate2ServerServerInfo m =
                    input.readMessage(
                        com.game.gate.proto.GateProto.Gate2ServerServerInfo.parser(),
                        extensionRegistry);
                if (serverInfoListBuilder_ == null) {
                  ensureServerInfoListIsMutable();
                  serverInfoList_.add(m);
                } else {
                  serverInfoListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo> serverInfoList_ =
        java.util.Collections.emptyList();
      private void ensureServerInfoListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          serverInfoList_ = new java.util.ArrayList<com.game.gate.proto.GateProto.Gate2ServerServerInfo>(serverInfoList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.gate.proto.GateProto.Gate2ServerServerInfo, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder, com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder> serverInfoListBuilder_;

      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo> getServerInfoListList() {
        if (serverInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(serverInfoList_);
        } else {
          return serverInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public int getServerInfoListCount() {
        if (serverInfoListBuilder_ == null) {
          return serverInfoList_.size();
        } else {
          return serverInfoListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo getServerInfoList(int index) {
        if (serverInfoListBuilder_ == null) {
          return serverInfoList_.get(index);
        } else {
          return serverInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder setServerInfoList(
          int index, com.game.gate.proto.GateProto.Gate2ServerServerInfo value) {
        if (serverInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfoListIsMutable();
          serverInfoList_.set(index, value);
          onChanged();
        } else {
          serverInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder setServerInfoList(
          int index, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder builderForValue) {
        if (serverInfoListBuilder_ == null) {
          ensureServerInfoListIsMutable();
          serverInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          serverInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder addServerInfoList(com.game.gate.proto.GateProto.Gate2ServerServerInfo value) {
        if (serverInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfoListIsMutable();
          serverInfoList_.add(value);
          onChanged();
        } else {
          serverInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder addServerInfoList(
          int index, com.game.gate.proto.GateProto.Gate2ServerServerInfo value) {
        if (serverInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerInfoListIsMutable();
          serverInfoList_.add(index, value);
          onChanged();
        } else {
          serverInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder addServerInfoList(
          com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder builderForValue) {
        if (serverInfoListBuilder_ == null) {
          ensureServerInfoListIsMutable();
          serverInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          serverInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder addServerInfoList(
          int index, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder builderForValue) {
        if (serverInfoListBuilder_ == null) {
          ensureServerInfoListIsMutable();
          serverInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          serverInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder addAllServerInfoList(
          java.lang.Iterable<? extends com.game.gate.proto.GateProto.Gate2ServerServerInfo> values) {
        if (serverInfoListBuilder_ == null) {
          ensureServerInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, serverInfoList_);
          onChanged();
        } else {
          serverInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder clearServerInfoList() {
        if (serverInfoListBuilder_ == null) {
          serverInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          serverInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public Builder removeServerInfoList(int index) {
        if (serverInfoListBuilder_ == null) {
          ensureServerInfoListIsMutable();
          serverInfoList_.remove(index);
          onChanged();
        } else {
          serverInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder getServerInfoListBuilder(
          int index) {
        return getServerInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder getServerInfoListOrBuilder(
          int index) {
        if (serverInfoListBuilder_ == null) {
          return serverInfoList_.get(index);  } else {
          return serverInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public java.util.List<? extends com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder> 
           getServerInfoListOrBuilderList() {
        if (serverInfoListBuilder_ != null) {
          return serverInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(serverInfoList_);
        }
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder addServerInfoListBuilder() {
        return getServerInfoListFieldBuilder().addBuilder(
            com.game.gate.proto.GateProto.Gate2ServerServerInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder addServerInfoListBuilder(
          int index) {
        return getServerInfoListFieldBuilder().addBuilder(
            index, com.game.gate.proto.GateProto.Gate2ServerServerInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 服务器信息
       * </pre>
       *
       * <code>repeated .Gate2ServerServerInfo serverInfoList = 1;</code>
       */
      public java.util.List<com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder> 
           getServerInfoListBuilderList() {
        return getServerInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.gate.proto.GateProto.Gate2ServerServerInfo, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder, com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder> 
          getServerInfoListFieldBuilder() {
        if (serverInfoListBuilder_ == null) {
          serverInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.gate.proto.GateProto.Gate2ServerServerInfo, com.game.gate.proto.GateProto.Gate2ServerServerInfo.Builder, com.game.gate.proto.GateProto.Gate2ServerServerInfoOrBuilder>(
                  serverInfoList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          serverInfoList_ = null;
        }
        return serverInfoListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ReqPublicRegisterServer)
    }

    // @@protoc_insertion_point(class_scope:ReqPublicRegisterServer)
    private static final com.game.gate.proto.GateProto.ReqPublicRegisterServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.gate.proto.GateProto.ReqPublicRegisterServer();
    }

    public static com.game.gate.proto.GateProto.ReqPublicRegisterServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqPublicRegisterServer>
        PARSER = new com.google.protobuf.AbstractParser<ReqPublicRegisterServer>() {
      @java.lang.Override
      public ReqPublicRegisterServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqPublicRegisterServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqPublicRegisterServer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.gate.proto.GateProto.ReqPublicRegisterServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResPublicGate2ServerConnectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResPublicGate2ServerConnect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0成功1失败
     * </pre>
     *
     * <code>int32 state = 1;</code>
     * @return The state.
     */
    int getState();
  }
  /**
   * <pre>
   * 返回服务器连接网关状态 msgId=201201
   * </pre>
   *
   * Protobuf type {@code ResPublicGate2ServerConnect}
   */
  public static final class ResPublicGate2ServerConnect extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResPublicGate2ServerConnect)
      ResPublicGate2ServerConnectOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResPublicGate2ServerConnect.class.getName());
    }
    // Use ResPublicGate2ServerConnect.newBuilder() to construct.
    private ResPublicGate2ServerConnect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResPublicGate2ServerConnect() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerConnect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerConnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.class, com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_ = 0;
    /**
     * <pre>
     * 0成功1失败
     * </pre>
     *
     * <code>int32 state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != 0) {
        output.writeInt32(1, state_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.gate.proto.GateProto.ResPublicGate2ServerConnect)) {
        return super.equals(obj);
      }
      com.game.gate.proto.GateProto.ResPublicGate2ServerConnect other = (com.game.gate.proto.GateProto.ResPublicGate2ServerConnect) obj;

      if (getState()
          != other.getState()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.gate.proto.GateProto.ResPublicGate2ServerConnect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 返回服务器连接网关状态 msgId=201201
     * </pre>
     *
     * Protobuf type {@code ResPublicGate2ServerConnect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResPublicGate2ServerConnect)
        com.game.gate.proto.GateProto.ResPublicGate2ServerConnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerConnect_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerConnect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.class, com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.Builder.class);
      }

      // Construct using com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        state_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerConnect_descriptor;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerConnect getDefaultInstanceForType() {
        return com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerConnect build() {
        com.game.gate.proto.GateProto.ResPublicGate2ServerConnect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerConnect buildPartial() {
        com.game.gate.proto.GateProto.ResPublicGate2ServerConnect result = new com.game.gate.proto.GateProto.ResPublicGate2ServerConnect(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.game.gate.proto.GateProto.ResPublicGate2ServerConnect result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.state_ = state_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.gate.proto.GateProto.ResPublicGate2ServerConnect) {
          return mergeFrom((com.game.gate.proto.GateProto.ResPublicGate2ServerConnect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.gate.proto.GateProto.ResPublicGate2ServerConnect other) {
        if (other == com.game.gate.proto.GateProto.ResPublicGate2ServerConnect.getDefaultInstance()) return this;
        if (other.getState() != 0) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                state_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int state_ ;
      /**
       * <pre>
       * 0成功1失败
       * </pre>
       *
       * <code>int32 state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return state_;
      }
      /**
       * <pre>
       * 0成功1失败
       * </pre>
       *
       * <code>int32 state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {

        state_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0成功1失败
       * </pre>
       *
       * <code>int32 state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResPublicGate2ServerConnect)
    }

    // @@protoc_insertion_point(class_scope:ResPublicGate2ServerConnect)
    private static final com.game.gate.proto.GateProto.ResPublicGate2ServerConnect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.gate.proto.GateProto.ResPublicGate2ServerConnect();
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerConnect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResPublicGate2ServerConnect>
        PARSER = new com.google.protobuf.AbstractParser<ResPublicGate2ServerConnect>() {
      @java.lang.Override
      public ResPublicGate2ServerConnect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResPublicGate2ServerConnect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResPublicGate2ServerConnect> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.gate.proto.GateProto.ResPublicGate2ServerConnect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResPublicGate2ServerHeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResPublicGate2ServerHeartbeat)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 网关to服务器之间心跳 msgId=201202
   * </pre>
   *
   * Protobuf type {@code ResPublicGate2ServerHeartbeat}
   */
  public static final class ResPublicGate2ServerHeartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResPublicGate2ServerHeartbeat)
      ResPublicGate2ServerHeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        ResPublicGate2ServerHeartbeat.class.getName());
    }
    // Use ResPublicGate2ServerHeartbeat.newBuilder() to construct.
    private ResPublicGate2ServerHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResPublicGate2ServerHeartbeat() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerHeartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.class, com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat)) {
        return super.equals(obj);
      }
      com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat other = (com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 网关to服务器之间心跳 msgId=201202
     * </pre>
     *
     * Protobuf type {@code ResPublicGate2ServerHeartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResPublicGate2ServerHeartbeat)
        com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerHeartbeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.class, com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.Builder.class);
      }

      // Construct using com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.gate.proto.GateProto.internal_static_ResPublicGate2ServerHeartbeat_descriptor;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat getDefaultInstanceForType() {
        return com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat build() {
        com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat buildPartial() {
        com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat result = new com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat) {
          return mergeFrom((com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat other) {
        if (other == com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResPublicGate2ServerHeartbeat)
    }

    // @@protoc_insertion_point(class_scope:ResPublicGate2ServerHeartbeat)
    private static final com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat();
    }

    public static com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResPublicGate2ServerHeartbeat>
        PARSER = new com.google.protobuf.AbstractParser<ResPublicGate2ServerHeartbeat>() {
      @java.lang.Override
      public ResPublicGate2ServerHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResPublicGate2ServerHeartbeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResPublicGate2ServerHeartbeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.gate.proto.GateProto.ResPublicGate2ServerHeartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Gate2ServerServerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Gate2ServerServerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqPublicRegisterServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqPublicRegisterServer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResPublicGate2ServerConnect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResPublicGate2ServerConnect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResPublicGate2ServerHeartbeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResPublicGate2ServerHeartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027publicGateMessage.proto\"U\n\025Gate2Server" +
      "ServerInfo\022\020\n\010serverId\030\001 \001(\005\022\022\n\nserverNa" +
      "me\030\002 \001(\t\022\026\n\016serverOpenTime\030\003 \001(\006\"I\n\027ReqP" +
      "ublicRegisterServer\022.\n\016serverInfoList\030\001 " +
      "\003(\0132\026.Gate2ServerServerInfo\",\n\033ResPublic" +
      "Gate2ServerConnect\022\r\n\005state\030\001 \001(\005\"\037\n\035Res" +
      "PublicGate2ServerHeartbeatB \n\023com.game.g" +
      "ate.protoB\tGateProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Gate2ServerServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Gate2ServerServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Gate2ServerServerInfo_descriptor,
        new java.lang.String[] { "ServerId", "ServerName", "ServerOpenTime", });
    internal_static_ReqPublicRegisterServer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReqPublicRegisterServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqPublicRegisterServer_descriptor,
        new java.lang.String[] { "ServerInfoList", });
    internal_static_ResPublicGate2ServerConnect_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResPublicGate2ServerConnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResPublicGate2ServerConnect_descriptor,
        new java.lang.String[] { "State", });
    internal_static_ResPublicGate2ServerHeartbeat_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResPublicGate2ServerHeartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResPublicGate2ServerHeartbeat_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
